# This file is used by Docker Dev Environment to create the dev container
services:
  app:
    entrypoint:
    - sleep
    - infinity
    build: 
      context: .
      target: base
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

