# This file is used by Docker Dev Environment to create the dev container
services:
  engine:
    # Infinite loop to keep the container running - use when you don't have a server running
    # entrypoint:
    # - sleep
    # - infinity
    build: 
      context: .
      target: base
    init: true
    restart: always
    privileged: true # Required to mount USB devices
    # devices:
    #   - "/dev/bus/usb:/dev/bus/usb"
      #- "/dev/usb:/dev/usb"
      #- "/dev:/dev"
    # cap_add:
    #   - SYS_ADMIN
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: .
        target: /engine
      - type: bind  # Required to see newly added USB devices
        source: /dev
        target: /dev
    command: bash -c "cd /engine && npm config set prefer-offline=true && pnpm run install_packages && pnpm run dev" 

